.TH PASS-STEAM 1 "2018 February 25" "Password store Steam extension"

.SH NAME
pass-steam - A \fBpass\fP(1) extension for managing Steam Guard codes.

.SH SYNOPSIS
.B pass steam
[
.I COMMAND
] [
.I OPTIONS
]... [
.I ARGS
]...

.SH DESCRIPTION

.B pass-steam
extends the
.BR pass (1)
utility with the
.B steam
command for adding Steam Guard secrets, generating Steam Guard codes, and displaying secret keys.

If no COMMAND is specified, COMMAND defaults to \fBcode\fP.

.SH COMMANDS

.TP
\fBsteam code\fP [ \fI--clip\fP, \fI-c\fP ] \fIpass-name\fP

Generate and print a Steam Guard code from the secret key stored in \fIpass-name\fP
using \fBoathtool\fP(1). If \fI--clip\fP or \fI-c\fP is specified, do not print
the code but instead copy it to the clipboard using \fBxclip\fP(1)
and then restore the clipboard after 45 (or \fIPASSWORD_STORE_CLIP_TIME\fP)
seconds. This command is alternatively named \fBshow\fP.

.TP
\fBsteam insert\fP [ \fI--force\fP, \fI-f\fP ] [ \fI--echo\fP, \fI-e\fP ] \
[ [ \fI--secret\fP, \fI-s\fP ] [ \fI--issuer\fP, \fI-i\fP \fIissuer\fP ] \
[ \fI--account\fP, \fI-a\fP \fIaccount\fP ] ] [ \fIpass-name\fP ]

Prompt for a new Steam Guard secret and insert it into the password store at
\fIpass-name\fP.

.SH OPTIONS

.TP
\fBhelp\fP, \fB\-h\fP, \fB\-\-help\fP
Show usage message.

.SH SEE ALSO
.BR pass (1)

.SH AUTHORS
.B pass-steam
was written by
.MT ivan@semkin.ru
Ivan Semkin
.ME .

.SH COPYING
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
