.TH PASS-STEAM 1 "2018 February 25" "Password store Steam extension"

.SH NAME
pass-steam - A \fBpass\fP(1) extension for managing Steam Guard codes.

.SH SYNOPSIS
.B pass steam
[
.I COMMAND
] [
.I OPTIONS
]... [
.I ARGS
]...

.SH DESCRIPTION

.B pass-steam
extends the
.BR pass (1)
utility with the
.B steam
command for adding Steam Guard secrets, generating Steam Guard codes, and displaying secret keys
URIs using the standard \fIsteamauth://\fP scheme.
