.TH PASS-STEAM 1 "2018 February 25" "Password store Steam extension"

.SH NAME
pass-steam - A \fBpass\fP(1) extension for managing Steam Guard codes.

.SH SYNOPSIS
.B pass steam
[
.I COMMAND
] [
.I OPTIONS
]... [
.I ARGS
]...

.SH DESCRIPTION

.B pass-steam
extends the
.BR pass (1)
utility with the
.B steam
command for adding Steam Guard secrets, generating Steam Guard codes, and displaying secret keys.

If no COMMAND is specified, COMMAND defaults to \fBcode\fP.

.SH COMMANDS

.TP
\fBsteam code\fP [ \fI--clip\fP, \fI-c\fP ] \fIpass-name\fP

Generate and print a Steam Guard code from the secret key stored in \fIpass-name\fP
using \fBoathtool\fP(1). If \fI--clip\fP or \fI-c\fP is specified, do not print
the code but instead copy it to the clipboard using \fBxclip\fP(1)
and then restore the clipboard after 45 (or \fIPASSWORD_STORE_CLIP_TIME\fP)
seconds. This command is alternatively named \fBshow\fP.
